### ISSUE TITLE
Can't run due to missing file

### ISSUE THREAD

**Issue by 55ahmedsalah** [Donny-Hikari/Viola-Jones#5]
FileNotFoundError: [Errno 2] No such file or directory: 'models/model-100-l7/x5large-2-variables.npy'

**Comment by Donny-Hikari** [comment]
It is the model file. You can generate this model file by training the model using `python train.py`. The training process requires image data to be placed in the data folder under the root folder. There are two types of images required, face images and non-face images. You can get these images from popular dataset, for example [FDDB](http://vis-www.cs.umass.edu/fddb/).
